### PR TITLE
add cmake support and use rdma-core-mummy to provide rdma-core

### PR DESCRIPTION
**Pull request by dragonJACson**

### CODE REVIEW

**Comment by FujiZ** [comment]
Try fixing some compile errors in https://github.com/RDMA-Rust/perftest/tree/fuji/cmake-support, but there are still some errors to be fixed:
图片

**Comment by dragonJACson** [comment]
> Try fixing some compile errors in https://github.com/RDMA-Rust/perftest/tree/fuji/cmake-support, but there are still some errors to be fixed: 图片

Just force pushed, could you please try again?

https://github.com/RDMA-Rust/perftest/compare/1838d4bb5097ffeb3641bab8cbc6c0d53546b252..7ef7fbf7902a206853031befca47636adb16a8e6

**Comment by FujiZ** [comment]
Resolve a compile error caused by `ibv_gid_type` and `ibv_gid_type_sysfs` in https://github.com/RDMA-Rust/perftest/tree/fix/gid-type

**Comment by dragonJACson** [comment]
> Resolve a compile error caused by `ibv_gid_type` and `ibv_gid_type_sysfs` in https://github.com/RDMA-Rust/perftest/tree/fix/gid-type

Cherry-picked this, thanks a lot!

**Review by FujiZ — APPROVED** [review]

**Pull request merged**
